version: "3.3"

services:
  # omniroom_frontend:
  #   container_name: omniroom_frontend
  #   build:
  #     context: ./services
  #     dockerfile: fe/Dockerfile
  #   volumes:
  #     - ./services/fe:/frontapp
  #   ports:
  #     - "8080:8080"
  #   logging:
  #     driver: none

  omniroom_db:
    container_name: "omniroom_db"
    restart: always
    build:
      context: ./services/be/db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=OmniRoom123456
      - POSTGRES_DB=OmniRoom
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: omniroom_redis
    restart: always
    ports:
      - "6378:6379"

  omniroom_backend:
    container_name: omniroom_backend
    restart: always
    build:
      context: ./services
      dockerfile: be/Dockerfile
    environment:
      - SMTP_PORT=$SMTP_PORT
      - SMTP_SERVER=$SMTP_SERVER
      - SENDER_EMAIL=$SENDER_EMAIL
      - SENDER_PASSWORD=$SENDER_PASSWORD
    volumes:
      - ./services/be:/app
    ports:
      - "5000:5000"
    depends_on:
      - omniroom_db
      - redis

volumes:
  pgdata: